/**
 * Secret-management surface for /app#/settings.
 *
 * The /setup/secrets/* endpoints let the user manage Worker secrets from
 * the browser without touching `wrangler secret put`. Under the hood:
 *
 *   PUT    /setup/secrets/<NAME>    — set/update a secret
 *   DELETE /setup/secrets/<NAME>    — drop it
 *   GET    /setup/secrets           — list known slots + current state
 *
 * All writes go through the Cloudflare API using CLOUDFLARE_API_TOKEN.
 * The names of writable secrets are bounded by `KNOWN_SECRETS` so a stolen
 * /app session can't exfiltrate the token by setting weird new keys —
 * we only let you set ones we explicitly recognize.
 */

import type { Env } from "./types";
import { AppError } from "./core/errors";

export type SecretGroup = "auth" | "providers" | "persistence" | "pa-stack" | "cf";

export interface SecretSlot {
  name: keyof Env;
  group: SecretGroup;
  label: string;
  /** Short description shown above the input. */
  hint: string;
  /** Hostname(s) the secret unlocks — surfaced so the user knows where to add to ALLOWED_HOSTS too. */
  allowedHost?: string;
  /** When true, render as a password field (most secrets); false for visible config like model names. */
  secret: boolean;
  /** When set, suggests a sensible default in the placeholder. */
  placeholder?: string;
  /** External link explaining where to find/generate this secret. */
  docsUrl?: string;
  /** When true, allow deletion via DELETE /setup/secrets/<name>. Some
   *  values (HELM_INTERNAL_TOKEN) we'd rather only rotate, not delete. */
  deletable?: boolean;
}

export const KNOWN_SECRETS: SecretSlot[] = [
  // --- auth ---
  {
    name: "AGENT_OWNER_EMAIL",
    group: "auth",
    label: "AGENT_OWNER_EMAIL",
    hint: "The email Cloudflare Access lets through. Auto-setup uses this for the email-allowlist policy.",
    secret: false,
    placeholder: "you@example.com"
  },
  {
    name: "OWNER_EMAIL",
    group: "auth",
    label: "OWNER_EMAIL",
    hint: "Alternative to AGENT_OWNER_EMAIL. Used by the email plugin for outbound notifications.",
    secret: false,
    placeholder: "you@example.com"
  },
  {
    name: "FROM_EMAIL",
    group: "auth",
    label: "FROM_EMAIL",
    hint: "Outbound email From: header. Must match a domain you own + Email-Routing-verified.",
    secret: false,
    placeholder: "helm@your-domain.com"
  },
  {
    name: "HELM_INTERNAL_TOKEN",
    group: "auth",
    label: "HELM_INTERNAL_TOKEN",
    hint: "Bearer the in-shell `helm` REPL uses. Auto-generated by /setup/auto. Rotate only when compromised.",
    secret: true,
    placeholder: "32-byte hex (auto-generated)",
    deletable: false
  },
  // --- CF infra ---
  {
    name: "CLOUDFLARE_API_TOKEN",
    group: "cf",
    label: "CLOUDFLARE_API_TOKEN",
    hint: "Scoped token (Workers/D1/Access/Account/User). Powers every /setup/* endpoint and the cloudflare-admin plugin.",
    secret: true,
    placeholder: "abcdef…",
    docsUrl: "https://dash.cloudflare.com/profile/api-tokens"
  },
  {
    name: "CLOUDFLARE_ACCOUNT_ID",
    group: "cf",
    label: "CLOUDFLARE_ACCOUNT_ID",
    hint: "Auto-detected from the token if you have only one account. Set explicitly to pin to a specific account.",
    secret: false,
    placeholder: "32-char hex"
  },
  {
    name: "AI_GATEWAY_ID",
    group: "cf",
    label: "AI_GATEWAY_ID",
    hint: "Cloudflare AI Gateway slug. Unlocks BYOK across 23+ providers via Secrets Store.",
    secret: false,
    placeholder: "my-gateway-id",
    docsUrl: "https://dash.cloudflare.com/?to=/:account/ai/ai-gateway"
  },
  {
    name: "AI_GATEWAY_AUTH_TOKEN",
    group: "cf",
    label: "AI_GATEWAY_AUTH_TOKEN",
    hint: "Optional — set if your AI Gateway is configured to require auth.",
    secret: true
  },
  // --- providers ---
  {
    name: "OPENROUTER_API_KEY",
    group: "providers",
    label: "OPENROUTER_API_KEY",
    hint: "When set, OpenRouter becomes the default chat provider with the auto-router. 100+ models, one key.",
    allowedHost: "openrouter.ai",
    secret: true,
    placeholder: "sk-or-…",
    docsUrl: "https://openrouter.ai/settings/keys"
  },
  {
    name: "OPENROUTER_DEFAULT_MODEL",
    group: "providers",
    label: "OPENROUTER_DEFAULT_MODEL",
    hint: "Pin a specific model. Default `openrouter/auto` picks per prompt.",
    secret: false,
    placeholder: "openrouter/auto"
  },
  {
    name: "ANTHROPIC_API_KEY",
    group: "providers",
    label: "ANTHROPIC_API_KEY",
    hint: "Direct path to Claude. Add api.anthropic.com to ALLOWED_HOSTS too.",
    allowedHost: "api.anthropic.com",
    secret: true,
    placeholder: "sk-ant-…",
    docsUrl: "https://console.anthropic.com/settings/keys"
  },
  {
    name: "OPENAI_API_KEY",
    group: "providers",
    label: "OPENAI_API_KEY",
    hint: "Classic OpenAI / Codex auth.",
    allowedHost: "api.openai.com",
    secret: true,
    placeholder: "sk-…",
    docsUrl: "https://platform.openai.com/api-keys"
  },
  {
    name: "OPENAI_COMPATIBLE_URL",
    group: "providers",
    label: "OPENAI_COMPATIBLE_URL",
    hint: "Base URL for any OpenAI-compatible endpoint (Groq, Together, Ollama, Cerebras, etc.).",
    secret: false,
    placeholder: "https://api.groq.com/openai/v1"
  },
  {
    name: "OPENAI_COMPATIBLE_KEY",
    group: "providers",
    label: "OPENAI_COMPATIBLE_KEY",
    hint: "API key for the OPENAI_COMPATIBLE_URL endpoint above.",
    secret: true
  },
  // --- persistence ---
  {
    name: "R2_BUCKET",
    group: "persistence",
    label: "R2_BUCKET",
    hint: "R2 bucket name for the /persist proxy. Auto-set by /setup/auto.",
    secret: false,
    placeholder: "helm-persist"
  },
  // --- artifacts (canonical wrangler.toml source-of-truth) ---
  {
    name: "ARTIFACTS_REPO",
    group: "persistence",
    label: "ARTIFACTS_REPO",
    hint: "Cloudflare Artifacts repo name. Auto-set by helm-setup-deploy to your Worker's name. Override only when you want a different name.",
    secret: false,
    placeholder: "(defaults to scriptName)"
  },
  {
    name: "ARTIFACTS_NAMESPACE",
    group: "persistence",
    label: "ARTIFACTS_NAMESPACE",
    hint: "Cloudflare Artifacts namespace. Defaults to \"default\" — only override for multi-tenant setups.",
    secret: false,
    placeholder: "default"
  },
  {
    name: "ARTIFACTS_BRANCH",
    group: "persistence",
    label: "ARTIFACTS_BRANCH",
    hint: "Default branch on the canonical Artifacts repo. \"main\" unless you have a reason to change it.",
    secret: false,
    placeholder: "main"
  },
  {
    name: "ARTIFACTS_TOKEN",
    group: "persistence",
    label: "ARTIFACTS_TOKEN",
    hint: "Power-user only — pre-minted long-lived Artifacts token. Leave blank and the plugin mints short-lived tokens on demand (more secure).",
    secret: true,
    placeholder: "art_v1_...?expires=..."
  },
  {
    name: "ARTIFACTS_AUTO_SYNC",
    group: "persistence",
    label: "ARTIFACTS_AUTO_SYNC",
    hint: "Set to \"1\" to have scheduled() run helm-artifacts-cron-sync on every cron firing (drift-check + notify).",
    secret: false,
    placeholder: "1"
  },
  {
    name: "R2_ACCESS_KEY_ID",
    group: "persistence",
    label: "R2_ACCESS_KEY_ID",
    hint: "Power-user only — needed if you want FUSE-mounted /persist inside the container. Otherwise leave blank.",
    secret: true,
    docsUrl: "https://dash.cloudflare.com/?to=/:account/r2/api-tokens"
  },
  {
    name: "R2_SECRET_ACCESS_KEY",
    group: "persistence",
    label: "R2_SECRET_ACCESS_KEY",
    hint: "Pair with R2_ACCESS_KEY_ID for FUSE-mounted /persist.",
    secret: true
  },
  // --- PA stack ---
  {
    name: "VAPID_PUBLIC_KEY",
    group: "pa-stack",
    label: "VAPID_PUBLIC_KEY",
    hint: "Generate with `npm run vapid:generate`. Required for Web Push.",
    secret: false
  },
  {
    name: "VAPID_PRIVATE_KEY",
    group: "pa-stack",
    label: "VAPID_PRIVATE_KEY",
    hint: "Generate with `npm run vapid:generate`. Pair with the public key above.",
    secret: true
  },
  {
    name: "VAPID_SUBJECT",
    group: "pa-stack",
    label: "VAPID_SUBJECT",
    hint: "RFC 8292 subject — must be a `mailto:` URL or HTTPS origin.",
    secret: false,
    placeholder: "mailto:you@example.com"
  },
  {
    name: "DAILY_SPEND_CAP_USD",
    group: "pa-stack",
    label: "DAILY_SPEND_CAP_USD",
    hint: "Hard daily ceiling on LLM spend. Empty = no cap. Recommended: $1–5 for personal use.",
    secret: false,
    placeholder: "5"
  },
  {
    name: "CALENDAR_MCP_URL",
    group: "pa-stack",
    label: "CALENDAR_MCP_URL",
    hint: "URL of a calendar MCP server. The calendar plugin proxies to it.",
    secret: false
  },
  {
    name: "MCP_DEFAULT_URL",
    group: "pa-stack",
    label: "MCP_DEFAULT_URL",
    hint: "Default MCP server URL. Point at https://mcp.cloudflare.com/mcp for chat-driven CF account ops.",
    secret: false,
    placeholder: "https://mcp.cloudflare.com/mcp"
  },
  {
    name: "MCP_BEARER_TOKEN",
    group: "pa-stack",
    label: "MCP_BEARER_TOKEN",
    hint: "Bearer for the MCP server above (when required).",
    secret: true
  }
];

const NAME_INDEX = new Map(KNOWN_SECRETS.map((s) => [s.name, s]));

export function getSecretSlot(name: string): SecretSlot | null {
  return NAME_INDEX.get(name as keyof Env) ?? null;
}

/**
 * Snapshot of every known slot + whether it's currently configured.
 * Values themselves are NEVER returned (this endpoint is read-only).
 */
export function listSecretStatus(env: Env): Array<{
  name: string;
  group: SecretGroup;
  label: string;
  hint: string;
  secret: boolean;
  configured: boolean;
  placeholder?: string;
  docsUrl?: string;
  deletable: boolean;
  allowedHost?: string;
}> {
  return KNOWN_SECRETS.map((s) => ({
    name: String(s.name),
    group: s.group,
    label: s.label,
    hint: s.hint,
    secret: s.secret,
    configured: Boolean(env[s.name]),
    placeholder: s.placeholder,
    docsUrl: s.docsUrl,
    deletable: s.deletable !== false,
    allowedHost: s.allowedHost
  }));
}

/**
 * Push a secret to the deployed Worker via the CF API. Caller is
 * responsible for resolving accountId + scriptName before this call.
 */
export async function putWorkerSecret(args: {
  apiToken: string;
  accountId: string;
  scriptName: string;
  name: string;
  value: string;
}): Promise<{ ok: boolean; error?: string }> {
  // Validate the name against our allowlist FIRST so a bad request
  // from the browser can't write arbitrary env vars.
  if (!getSecretSlot(args.name)) {
    return {
      ok: false,
      error: `Unknown secret name "${args.name}". Allowed: ${KNOWN_SECRETS.map((s) => String(s.name)).join(", ")}`
    };
  }
  const r = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(
      args.accountId
    )}/workers/scripts/${encodeURIComponent(args.scriptName)}/secrets`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${args.apiToken}`,
        "content-type": "application/json"
      },
      body: JSON.stringify({
        name: args.name,
        text: args.value,
        type: "secret_text"
      })
    }
  );
  if (!r.ok) {
    const text = await r.text();
    return { ok: false, error: `cf-api ${r.status}: ${text.slice(0, 300)}` };
  }
  return { ok: true };
}

export async function deleteWorkerSecret(args: {
  apiToken: string;
  accountId: string;
  scriptName: string;
  name: string;
}): Promise<{ ok: boolean; error?: string }> {
  const slot = getSecretSlot(args.name);
  if (!slot) {
    return { ok: false, error: `Unknown secret name "${args.name}"` };
  }
  if (slot.deletable === false) {
    return {
      ok: false,
      error: `Secret "${args.name}" is marked non-deletable. Rotate via PUT instead.`
    };
  }
  const r = await fetch(
    `https://api.cloudflare.com/client/v4/accounts/${encodeURIComponent(
      args.accountId
    )}/workers/scripts/${encodeURIComponent(args.scriptName)}/secrets/${encodeURIComponent(args.name)}`,
    {
      method: "DELETE",
      headers: { Authorization: `Bearer ${args.apiToken}` }
    }
  );
  if (!r.ok) {
    const text = await r.text();
    return { ok: false, error: `cf-api ${r.status}: ${text.slice(0, 300)}` };
  }
  return { ok: true };
}

/** Resolve accountId from env, throwing E_BAD_REQUEST if unset. */
export function resolveAccountId(env: Env): string {
  const id = env.CLOUDFLARE_ACCOUNT_ID;
  if (!id) {
    throw new AppError(
      "E_ACCOUNT_ID_MISSING",
      "CLOUDFLARE_ACCOUNT_ID is not set. Run /setup/auto or paste it via the secrets manager.",
      400
    );
  }
  return id;
}
